# -*- coding: utf-8 -*-
"""
Bot static messages in Uzbek.
"""

# Common
WELCOME = (
    "Assalomu alaykum! Botimizga xush kelibsiz.\n\n"
    "Bu bot orqali mahsulot postlarini reja bo'yicha guruhga joylaysiz."
)
# Oddiy user guruh posti orqali kirmaganda (faqat /start)
WELCOME_USER_ONLY_VIA_GROUP = (
    "Assalomu alaykum!\n\n"
    "Mahsulot haqida batafsil ma'lumot olish uchun guruhimizdagi ma'lumotlardan foydalaning."
)
USER_SIMPLE_REPLY = (
    "Mahsulot haqida bilmoqchi bo'lsangiz guruhimizda adminlar haqida ma'lumotlar orqali bog'laning !"
)
POST_ADD_USE_BUTTON_HINT = "Post qo'shish uchun «Post qo'shish» yoki «Matnli post qo'shish» tugmasini bosing."
BACK = "Orqaga"

# Admin / Owner
HELP_HEADER = "Yordam"
HELP_GUIDE = (
    "📌 Post qo'shish — «➕ Post qo'shish» tugmasi: rasm, video yoki matn yuboring, ixtiyoriy caption, «Yakunlash», "
    "so'ng nashr vaqtini (soat va minut) tanlang. «📝 Matnli post qo'shish» — faqat matn uchun alohida oqim.\n\n"
    "📜 Postlar tarixi — oxirgi qo'shilgan postlar ro'yxati, har bir post ostida O'chirish tugmasi. Qo'shish/o'chirishda ro'yxat qayta yuborilmaydi.\n\n"
    "📢 Nashr guruhi — postlar yuboriladigan guruh. Sozlash: guruhda yoki shaxsiy chatda tegishli tugma/menyu orqali.\n\n"
    "👤 Adminlar — faqat egasi admin qo'shadi yoki olib tashlaydi (adminlar ro'yxati va tegishli tugmalar orqali)."
)
ADD_TEXT_EMPTY = "Matn kiriting. Masalan: /add_text Reklama matni shu yerda"

# Schedule / groups
TIMES_SET = "Nashr vaqtlari yangilandi."
TARGET_GROUP_SET = "Nashr guruhi o'rnatildi."
TARGET_GROUP_PROMPT_ID = "Nashr guruhi ID sini kiriting (masalan -1001234567890):"
TARGET_GROUP_ID_RECEIVED = "ID qabul qilindi. Botni shu guruhga qo'shing va admin sifatida qo'ying. Keyin tasdiqlang."
BTN_CONFIRM_TARGET_GROUP = "Guruhni belgilash"
ADMIN_GROUP_SET = "Admin guruhi o'rnatildi."
ADMIN_GROUP_PROMPT_ID = "Lead guruhi ID sini kiriting (masalan -1001234567890):"
ADMIN_GROUP_ID_RECEIVED = "ID qabul qilindi. Botni shu guruhga qo'shing va admin qiling. Keyin tasdiqlang."
BTN_CONFIRM_ADMIN_GROUP = "Guruhni belgilash"
GROUP_ID_SHOULD_BE_NEGATIVE = "Guruh ID odatda manfiy bo'ladi (masalan -1001234567890). Iltimos, guruhda /set_target_group yuborib oling yoki to'g'ri manfiy ID kiriting."
CONTENT_SAVED = "Kontent saqlandi va aktiv post sifatida belgilandi."
NO_ACTIVE_CONTENT = "Aktiv post yo'q. Avval kontent yuboring (rasm, video yoki matn)."
# Post qo'shish oqimi
BTN_ADD_POST = "➕ Post qo'shish"
BTN_ADD_TEXT_POST = "📝 Matnli post qo'shish"
TEXT_POST_SEND_PROMPT = "Matnli post uchun matnni yuboring."
POST_ADD_SEND_MEDIA = "Post uchun rasm, video yoki matn yuboring."
POST_ADD_SEND_CAPTION = "Matn (caption) yozing (ixtiyoriy) yoki «Yakunlash» tugmasini bosing."
POST_ADD_CAPTION_ADDED = "Matn qo'shildi. «Yakunlash» tugmasini bosing."
POST_ADD_SAVED = "Post saqlandi va aktiv post sifatida belgilandi."
POST_ADD_CANCELLED = "Bekor qilindi."
POST_ADD_ALREADY_PENDING = "Sizda allaqachon post kutilmoqda. Avval «Yakunlash» yoki «Bekor qilish» ni bosing, keyin yangi matn yuboring."
POST_ADD_PICK_TIME_HOUR = "Nashr vaqtini tanlang: soat"
POST_ADD_PICK_TIME_MINUTE = "Minut tanlang"
BTN_POST_CONFIRM = "✅ Yakunlash"
BTN_POST_CANCEL = "❌ Bekor qilish"
HISTORY_HEADER = "Postlar tarixi (oxirgi 10):"
BTN_HISTORY_BACK = "◀️ Orqaga"
POST_DELETED = "Post o'chirildi (endi nashr etilmaydi)."
POST_NOT_FOUND = "Bunday post topilmadi yoki allaqachon o'chirilgan."
SCHEDULE_ADDED = "Vaqt qo'shildi: {}"
SCHEDULE_REMOVED = "Vaqt olib tashlandi: {}"
SCHEDULE_INVALID = "Vaqt noto'g'ri. Masalan: 09:00 yoki 14:30"
CURRENT_TIMES = "Joriy post joylash vaqtlari: {}"
SCHEDULE_ADD_TIME_HINT = "Post joylash uchun yangi vaqtni 09:00 formatida yuboring yoki /set_times 09:00 12:00 buyrug'ini ishlating."
SCHEDULE_PICK_HOUR = "Soatni tanlang"
SCHEDULE_PICK_MINUTE = "Minutni tanlang"
SCHEDULE_TIME_ADDED = "Vaqt qo'shildi."
ADMIN_ADDED = "Admin qo'shildi."
ADMIN_REMOVED = "Admin olib tashlandi."
ADMIN_ALREADY = "Bu foydalanuvchi allaqachon admin."
ADMIN_NOT_FOUND = "Admin topilmadi."
REPLY_TO_ADD_ADMIN = "Admin qo'shish uchun foydalanuvchi xabariga reply qiling va /add_admin yozing."
ADMIN_ADD_PROMPT = (
    "Yangi adminning Telegram ID sini kiriting (faqat raqam, masalan 123456789). "
    "ID ni @userinfobot orqali olish mumkin."
)
ADMIN_ADD_INVALID_ID = "Faqat raqam (Telegram ID) kiriting. Masalan: 123456789"
REPLY_TO_REMOVE_ADMIN = "Adminni olib tashlash uchun uning xabariga reply qiling va /remove_admin yozing."
OWNER_ONLY = "Bu buyruqni faqat bot egasi ishlata oladi."
ADMIN_ONLY = "Bu buyruqni faqat adminlar ishlata oladi."
LIST_ADMINS_HEADER = "Adminlar:"

# Reply / Inline button labels
BTN_USER_WRITE = "📩 Xabar yuborish"
BTN_HELP = "📋 Yordam"
BTN_HISTORY = "📜 Postlar tarixi"
BTN_SCHEDULE = "⏰ Post vaqtlari"
BTN_TARGET_GROUP = "📢 Nashr guruhi"
BTN_LEAD_GROUP = "👥 Lead guruhi"
BTN_ADMINS = "👤 Adminlar"
BTN_USER_ADMINS = "👥 Adminlar ro'yxati"
BTN_ADMIN_LIST = "Ro'yxat"
BTN_ADMIN_ADD_HINT = "Qo'shish (reply)"
BTN_ADMIN_REMOVE_HINT = "O'chirish (reply)"
BTN_BACK = "◀️ Orqaga"
BTN_REFRESH_HISTORY = "🔄 Yangilash"
BTN_ADD_TIME = "➕ Vaqt qo'shish"
BTN_INLINE_HISTORY = "📜 Postlar tarixi"
BTN_INLINE_SCHEDULE = "⏰ Nashr vaqtlari"
BTN_POST_NOW = "Hozir joylash"
POST_NOW_SUCCESS = "Post guruhga yuborildi."
POST_NOW_FAILED = "Post yuborish amalga oshmadi (guruh yoki kontent tekshiring)."
POST_NOT_ASSIGNED = "Post tanlanmagan"
SCHEDULE_ASSIGNED = "Post vaqtga biriktirildi."
SCHEDULE_PICK_POST_HEADER = "Ushbu vaqt uchun post tanlang:"
NASHR_TIMES_LABEL = "Post joylash vaqtlari:"
PUBLISHING_ENABLED = "Nashr yoqilgan"
PUBLISHING_DISABLED = "Nashr o'chirilgan"
BTN_PUBLISHING_ON = "Nashr yoqish"
BTN_PUBLISHING_OFF = "Nashr o'chirish"
USER_WRITE_HINT = "Quyida xabaringizni yozing — adminlar ko'radi va javob beradi."
USER_PICK_PRODUCT = "Qaysi mahsulot (post) haqida yozmoqchisiz? Quyidagilardan birini tanlang yoki «Umumiy savol» ni bosing."
USER_CONTACT_RECEIVED = "Raqam qabul qilindi. Endi xabaringizni yuboring."
USER_ADMINS_LIST_HEADER = "Adminlar bilan bog'lanish uchun quyidagi tugmalar orqali chatga o'ting."
BTN_NAV_BACK = "◀️ Orqaga"
BTN_NAV_HOME = "🏠 Bosh menyu"
BTN_NAV_REFRESH = "🔄 Yangilash"
